services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - python_app
    networks:
      - addressnet

  python_app:
    build: ./python_app
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - addressnet
    environment:
      FLASK_DEBUG: ${FLASK_DEBUG}

  postgres:
    image: postgres:13
    networks:
      - addressnet
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:

networks:
  addressnet:
