apiVersion: v1
data:
  nginx.conf: |
    events { }

    http {
        server {
            listen 80;
            location / {
                proxy_pass http://app:5000;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
        }
    }
kind: ConfigMap
metadata:
  creationTimestamp: "2024-07-23T02:43:56Z"
  name: nginx-config
  namespace: default
  resourceVersion: "3082"
  uid: adff9c67-6988-42fa-9f9b-41aba1477385
