name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    tags:
      - '*'
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract branch or tag name
      id: extract_ref
      run: |
        if [[ "${GITHUB_REF}" == refs/heads/* ]]; then
          echo "##[set-output name=ref_name;]${GITHUB_REF#refs/heads/}"
        elif [[ "${GITHUB_REF}" == refs/tags/* ]]; then
          echo "##[set-output name=ref_name;]${GITHUB_REF#refs/tags/}"
        else
          echo "##[set-output name=ref_name;]unknown"
        fi

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v6
      with:
        context: ./app
        file: ./app/Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/address-book:latest
          ghcr.io/${{ github.repository_owner }}/address-book:${{ steps.extract_ref.outputs.ref_name }}

    - name: Logout from GitHub Container Registry
      run: docker logout ghcr.io
