name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch or tag to build from'
        required: true
        default: 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.ref || github.ref }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}  # Or use GHCR_PAT if using a PAT

    - name: Extract branch or tag name
      id: extract_ref
      run: |
        if [[ "${GITHUB_REF}" == refs/heads/* ]]; then
          echo "ref_name=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
        elif [[ "${GITHUB_REF}" == refs/tags/* ]]; then
          echo "ref_name=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        elif [[ "${{ github.event.inputs.ref }}" != "" ]]; then
          echo "ref_name=${{ github.event.inputs.ref }}" >> $GITHUB_ENV
        else
          echo "ref_name=unknown" >> $GITHUB_ENV
        fi

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: ./app
        file: ./app/Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/address-book:latest
          ghcr.io/${{ github.repository_owner }}/address-book:${{ env.ref_name }}

    - name: Logout from GitHub Container Registry
      run: docker logout ghcr.io
